### ISSUE TITLE
It is not really working

### ISSUE THREAD

**Issue by franzberge** [Swiss-Mac-User/language-locale-overwrite#2]
Hi i am quite in the field of Wordpress.
I found your plug in which is very interesting to me.

I only find a php file to download . Which if I move it to the plugin folder is not shown in the dashboard.

I i convert the php into Zip with a converter. The website sends me the following message:

Hallo!

WordPress hat eine eingebaute Funktion, die erkennt, wenn ein Plugin oder ein Theme einen fatalen Fehler auf deiner Website verursacht, und dich deswegen mit dieser automatisierten E-Mail benachrichtigt.

.... 
What do you think, do I make mistake?

**Comment by Swiss-Mac-User** [comment]
@franzberge thanks for reporting this. Seems to cause a hard crash on certain WP setups. I will look into it, and what conditions might cause this.

**Comment by Swiss-Mac-User** [comment]
@franzberge upon reviewing your issue again, it sounds like you've installed the plugin wrongly. Please remove the files / zip file you added, that causes problems.


Then try this please:

1. Download ZIP file from «Releases» here: https://github.com/Swiss-Mac-User/language-locale-overwrite/releases
2. Unzip the ZIP file. You should have a folder called "language-locale-overwrite"
3. Move this _whole folder_ to your Wordpress installation into the directory `<your-blog>/wp-content/wp-plugins/`
4. Now open your Wordpress site & see if everything works
5. Go to your Wordpress Admin area > Plugins and activate the Plugin from the list

Hope that helps.

**Comment by franzberge** [comment]
Hi, i have tried several options.
Moving the entire folder in the Wp/plugin folder and install the ZIP in the AddPlugin Wordpress option.
Unfortunately it doesn't work as far may ability goes.

Thank you for your help, Franz


Franz Trimmel
UIAGM Mountain and Ski Guide
Höhenstrasse 113
6020 Innsbruck
St. Anton
+436643937764
alloffpiste.com
allesklettersteig.com
franzderberge.at

**Comment by Swiss-Mac-User** [comment]
Hi @franzberge 
I had another person reporting a similar issue, and was able to send me the details what WordPress is "complaining" about.

So here's **a new version 2.1.0 available now**, also with a ZIP-file that you can extract & move directly into your blog's `/wp-content/wp-plugins/` folder: https://github.com/Swiss-Mac-User/language-locale-overwrite/releases/tag/2.1.0

Hope it works now for you as well 🤞

**Comment by franzberge** [comment]
Thank you for all your hard work.
I found a Article from Google Webmaster that google is ignoring the HTML Lang.
https://www.seroundtable.com/google-ignores-the-html-lang-attribute-22974.html

I did it with:
<link rel="alternate" href="https://allesklettersteig.com/en" hreflang="en-GB">
<link rel="alternate" href="https://allesklettersteig.com/en" hreflang="en-US">

As Hook Element on the individual Website.
It works fine and there is no hustle.

**Comment by Swiss-Mac-User** [comment]
> I found a Article from Google Webmaster that google is ignoring the HTML Lang.

Thanks for sharing & yes that's true, Google works with the `hreflang` attributes. The HTML `lang` is for better user experience: accessibility on devices and browsers that read it to offer possible translations of pages when the visitor's system language differs from the website content they are viewing.
