### ISSUE TITLE
request: ability to change language declaration for auto-generated pages such as categories

### ISSUE THREAD

**Issue by catharsis71** [Swiss-Mac-User/language-locale-overwrite#5]
as far as I can tell it's not currently possible to change the language declaration for a category listing page

perhaps something could be added to the "edit category" screen?

maybe on "edit tag" as well?

**Comment by Swiss-Mac-User** [comment]
This has been added in the [latest Release](https://github.com/Swiss-Mac-User/language-locale-overwrite/releases/tag/2.3.0).

It works slightly different than anticipated, though:

* Defining a custom language locale on a Category or Tag is only used to attribute the corresponding Archive page's title & description with the custom locale! But this does not inherit to all Posts categorized by it nor the whole Category archive page.
* However, every Post preview shown _on_ Archive pages (like categories or tags) now also has its custom language locale attributed for the post/page title and excerpt snippets.

The reason being:

Attributing a whole page with a lang-attribute indicates that everything on _that_ page is translated; including Labels, Footer, etc. This is not something that this Plugin is meant for and neither supports doing.
